name: opencv_histogram_equality
description: Created for calculate image histogram equality.
version: 0.0.1+1
author:
homepage: https://github.com/chapterinc/opencv-histogram-equality

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.opencv.histogram.opencv_histogram_equality
        pluginClass: OpencvHistogramEqualityPlugin
      ios:
        pluginClass: OpencvHistogramEqualityPlugin

